name: Build & Deploy to DigitalOcean via Docker Registry

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image to registry
      run: docker push $IMAGE_NAME

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into server and run container
      run: |
        ssh ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << EOF
          docker pull $IMAGE_NAME
          docker stop fastapi-container || true
          docker rm fastapi-container || true
          docker run -d --name fastapi-container -p 8000:8000 $IMAGE_NAME
        EOF